#= require jquery
#= require jquery-ui/widgets/datepicker
#= require jquery-ui/widgets/sortable
#= require jquery_ujs
#= require jquery.remotipart
#= require jquery.slick
#= require vue
#= require select2-full
#= require select2_locale_es
#= require keppler_frontend/app/file_uploader
#= require keppler_frontend/app/sweetalert3/sweetalert2.all.min
#= require keppler_frontend/app/sweetalert3/delete-confirm
#= require keppler_frontend/app/select2/select2.full.min
#= require keppler_frontend/app/notification
#= require keppler_frontend/app/main
# require_tree .
