menu:
  dashboard:
    name: dashboard
    url_path: /admin
    icon: dashboard
    current: ['admin/dashboard']
    model: Dashboard
  script:
    name: scripts
    url_path: /admin/scripts
    icon: code
    current: ['admin/scripts']
    model: Script
    environment: development
  seo:
    name: Seo
    current: ['admin/meta_tags']
    icon: chart
    model: Seo
    url_path: /admin/meta_tags
    environment: development
    submenu:
      - metatag:
          name: metatags
          url_path: /admin/meta_tags
          current: ['admin/meta_tags']
          model: MetaTag
      - sitemap:
          name: sitemap
          url_path: /admin/seo/sitemap
          current: ['admin/seo/sitemap']
          environment: development
          model: Seo
      - robots:
          name: robots
          url_path: /admin/seo/robots
          current: ['/admin/seo/robots']
          environment: development
          model: Seo
  user:
    name: users
    icon: user
    current: ['admin/users', 'admin/roles']
    model: User
    submenu:
      - user:
          name: users
          url_path: /admin/users
          current: ['admin/users']
          model: User
      - role:
          name: roles
          url_path: /admin/roles
          current: ['admin/roles']
          model: Role
  rockets:
    name: rockets
    icon: rocket
    current: ['/admin/rockets']
    model: Rocket
    environment: development
    url_path: /admin/rockets
