menu:
  keppler_farm:
    name: Keppler Farm
    current: ['/']
    url_path: /
    icon: rocket
    model: User
    submenu:
      - ground:
          name: ground
          url_path: /admin/farm/grounds
          icon: layers
          current: ['/admin/farm/grounds']
          model: KepplerFarm::Ground

      - responsable:
          name: responsable
          url_path: /admin/farm/responsables
          icon: layers
          current: ['/admin/farm/responsables']
          model: KepplerFarm::Responsable


      - farm:
          name: farm
          url_path: /admin/farm/farms
          icon: layers
          current: ['/admin/farm/farms']
          model: KepplerFarm::Farm
      - process:
          name: process
          url_path: /admin/farm/processes
          icon: layers
          current: ['/admin/farm/processes']
          model: KepplerFarm::Process