modules:
  photos:
    name: Photo
    model: KepplerFarmPhoto
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  processes:
    name: Process
    model: KepplerFarmProcess
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  farms:
    name: Farm
    model: KepplerFarmFarm
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
