menu:
  keppler_cattle:
    name: Cattle
    current: ['/']
    url_path: /
    icon: rocket
    model: KepplerCattle::Cow
    submenu:
      - inventory_cow:
          name: inventory cow
          url_path: /admin/cattle/inventory_cows
          icon: layers
          current: ['/admin/cattle/inventory_cows']
          model: KepplerCattle::InventoryCow

      # - inventory:
      #     name: inventory
      #     url_path: /admin/cattle/inventories
      #     icon: layers
      #     current: ['/admin/cattle/inventories']
      #     model: KepplerCattle::Inventory


      - cow:
          name: cow
          url_path: /admin/cattle/cows
          icon: layers
          current: ['/admin/cattle/cows']
          model: KepplerCattle::Cow

      - transference:
          name: transference
          url_path: /admin/cattle/transferences
          icon: layers
          current: ['/admin/cattle/transferences']
          model: KepplerCattle::Transference

      - species:
          name: species
          url_path: /admin/cattle/species
          icon: layers
          current: ['/admin/cattle/species']
          model: KepplerCattle::Species

      - insemination:
          name: insemination
          url_path: /admin/cattle/inseminations
          icon: layers
          current: ['/admin/cattle/inseminations']
          model: KepplerCattle::Insemination
