menu:
  keppler_cattle:
    name: Cattle
    current: ['/']
    url_path: /
    icon: rocket
    model: User
    submenu:
      - cow:
          name: cow
          url_path: /admin/cattle/cows
          icon: layers
          current: ['/admin/cattle/cows']
          model: KepplerCattle::Cow

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User