modules:
  medical_histories:
    name: MedicalHistory
    model: KepplerCattleMedicalHistory
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  inseminations:
    name: Insemination
    model: KepplerCattleInsemination
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  species:
    name: Species
    model: KepplerCattleSpecies
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  weighing_days:
    name: WeighingDay
    model: KepplerCattleWeighingDay
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  typologies:
    name: Typology
    model: KepplerCattleTypology
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  races:
    name: Race
    model: KepplerCattleRace
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  transferences:
    name: Transference
    model: KepplerCattleTransference
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  statuses:
    name: Status
    model: KepplerCattleStatus
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  cows:
    name: Cow
    model: KepplerCattleCow
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
